import { EventItem } from "./types";

export const mockEvents: EventItem[] = [
  {
    _id: "evt-salsa-sunday",
    id: "evt-salsa-sunday",
    title: "Salsa Sundays",
    description:
      "Beginner-friendly salsa social with live percussion and pro instructors.",
    price: 899,
    photo: "/images/salsa.jpg",
    images: ["/images/salsa.jpg"],
    media: ["/images/salsa.jpg"],
    venue: "All Stars Studio",
    category: "Social",
    about: [
      {
        title: "What to expect",
        description:
          "Warm-up, partner fundamentals, and a social set with live percussion.",
        images: ["/images/salsa.jpg"],
      },
    ],
    placename: "All Stars Studio",
    date: "2026-02-02",
    time: "18:00",
    location: "All Stars Studio, Mumbai",
    type: "event",
    isActive: true,
  },
  {
    _id: "cls-hiphop",
    id: "cls-hiphop",
    title: "Hip-Hop Foundation Class",
    description: "Drills, grooves, and choreography for all levels.",
    price: 699,
    photo: "/images/hiphop.jpg",
    images: ["/images/hiphop.jpg"],
    media: ["/images/hiphop.jpg"],
    venue: "Khar Studio",
    category: "Workshop",
    about: [
      {
        title: "Class flow",
        description: "Foundation drills followed by choreography practice.",
        images: ["/images/hiphop.jpg"],
      },
    ],
    placename: "Khar Studio",
    date: "2026-02-05",
    time: "19:30",
    location: "Khar Studio, Mumbai",
    type: "class",
    isActive: true,
  },
  {
    _id: "evt-bachata-night",
    id: "evt-bachata-night",
    title: "Bachata Night & Workshop",
    description:
      "Sensual bachata workshop followed by social dancing and DJ set.",
    price: 1199,
    photo: "/images/bachata.jpg",
    images: ["/images/bachata.jpg"],
    media: ["/images/bachata.jpg"],
    venue: "Soho House",
    category: "Night",
    about: [
      {
        title: "Workshop",
        description: "Focus on technique and connection with guided practice.",
        images: ["/images/bachata.jpg"],
      },
    ],
    placename: "Soho House",
    date: "2026-02-10",
    time: "20:00",
    location: "Soho House, Mumbai",
    type: "event",
    isActive: true,
  },
  {
    _id: "cls-contemporary",
    id: "cls-contemporary",
    title: "Contemporary Flow",
    description: "Floor work, lines, and musicality with guest choreographer.",
    price: 950,
    photo: "/images/contemporary.jpg",
    images: ["/images/contemporary.jpg"],
    media: ["/images/contemporary.jpg"],
    venue: "Bandra Studio",
    category: "Class",
    about: [
      {
        title: "Movement focus",
        description: "Lines, musicality, and floor-work fundamentals.",
        images: ["/images/contemporary.jpg"],
      },
    ],
    placename: "Bandra Studio",
    date: "2026-02-12",
    time: "17:00",
    location: "Bandra Studio, Mumbai",
    type: "class",
    isActive: true,
  },
];
